name: Build binaries & release

on:
  push:
    branches:
      - master

jobs:

  node14-linux-x64:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm ci
      - run: npm run build::${{ github.job }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: bin

  node14-windows-x64:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm ci
      - run: npm run build::${{ github.job }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: bin

  node14-macos-x64:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm ci
      - run: npm run build::${{ github.job }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: bin


  create_release:
    runs-on: ubuntu-20.04
    needs:
      - node14-linux-x64
      - node14-windows-x64
      - node14-macos-x64

    steps:
      - uses: actions/download-artifact@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            bin/*
